stages:
  - deploy

deploy_job:
  stage: deploy
  script:
    - rm -Rf /home/admin/web/devst.fishlab.su/public_html/$CI_PROJECT_NAME/
    - cp -R ./build/ /home/admin/web/devst.fishlab.su/public_html/$CI_PROJECT_NAME/